version: '3'

volumes:
  postgresql:
  minio:

#networks:
#  blog-server:
#    driver: bridge

services:
  postgres:
    container_name: pg_blog
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    volumes:
      - ./postgres_logs:/var/lib/postgresql/logs
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - postgresql:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: on-failure
    ports:
      - "5432:5432"

  minio:
    container_name: minio_blog
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: 123456789
    ports:
      - "9001:9001"
      - "9000:9000"
    command: server --console-address ":9001" /data
    volumes:
      - minio:/data